pref("extensions.{3550f703-e582-4d05-9a08-453d09bdfdc6}.description", "chrome://quickfolders/locale/quickfolders.properties");
pref("extensions.quickfolders.showShortcutNumber",true);
pref("extensions.quickfolders.showUnreadOnButtons",true);
pref("extensions.quickfolders.showQuickfoldersLabel",true);
pref("extensions.quickfolders.showUnreadFoldersBold",true);
pref("extensions.quickfolders.useKeyboardShortcuts",true);
pref("extensions.quickfolders.useKeyboardShortcutCTRL",false);
pref("extensions.quickfolders.showTotalNumber",false);
pref("extensions.quickfolders.showFoldersWithMessagesItalic",false);
pref("extensions.quickfolders.showFlatStyle",true);
pref("extensions.quickfolders.showNativeTabStyle",false);
pref("extensions.quickfolders.autoFocusPreview",true);
pref("extensions.quickfolders.buttonFontSize","");
pref("extensions.quickfolders.lastSelectedCategory","");
pref("extensions.quickfolders.showIcons",false);
pref("extensions.quickfolders.debug",false);
pref("extensions.quickfolders.initDelay", 5000);
pref("extensions.quickfolders.colorTabStyle",0);
pref("extensions.quickfolders.showSubfolders",false);
pref("extensions.quickfolders.queuedFolderUpdateDelay",500);
pref("extensions.quickfolders.debug.css",false);
pref("extensions.quickfolders.debug.dnd",false);
pref("extensions.quickfolders.debug.folders",false);
pref("extensions.quickfolders.debug.popupmenus",false);
pref("extensions.quickfolders.debug.events",false);
pref("extensions.quickfolders.debug.mailTabs",false);

