pref("extensions.{3550f703-e582-4d05-9a08-453d09bdfdc6}.description", "chrome://quickfolders/locale/quickfolders.properties");
pref("extensions.quickfolders.showShortcutNumber",true);
pref("extensions.quickfolders.showUnreadOnButtons",true);
pref("extensions.quickfolders.showQuickfoldersLabel",false);
pref("extensions.quickfolders.showUnreadFoldersBold",true);
pref("extensions.quickfolders.useKeyboardShortcuts",true);
pref("extensions.quickfolders.showTotalNumber",false);
pref("extensions.quickfolders.showFoldersWithMessagesItalic",false);
pref("extensions.quickfolders.showFlatStyle",true);
pref("extensions.quickfolders.buttonFontSize","");
pref("extensions.quickfolders.lastSelectedCategory","");
pref("extensions.quickfolders.showIcons",false);
pref("extensions.quickfolders.debug",false);
